# Generated by Django 4.1.7 on 2023-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ending_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
