# Generated by Django 4.1.7 on 2023-03-21 18:26

from django.db import migrations, models


def insert_data(apps, schema_editor):
    Model = apps.get_model("users", "UserCategories")
    categories = [
        'Client',
        'Architect',
        'Engineer',
    ]
    for category in categories:
        user_cat = Model(title_of_user=category)
        user_cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
